### ISSUE TITLE
Cómo lo puedo instalar en Ubuntu?

### ISSUE THREAD

**Issue by johnfelipe** [YagoLopez/Webcams_de_Asturias#1]

**Comment by YagoLopez** [comment]
Hola @johnfelipe. No te lo puedo garantizar porque no tengo Ubuntu para comprobarlo, pero no debería ser difícil.

En principio bastaría con tener un servidor web que apuntara al fichero `/www/index.html`. Es decir, tendrías que clonar el repositorio o descargar el zip y hacer visible el directorio `/www/index.html` en tu servidor web. El resto de carpetas del proyecto las podrías borrar. Supongo que Ubuntu tendrá algún servidor web o la posibilidad de instalarlo como paquete.

Puedes descargar el zip usando el boton de color verde que pone "Clone or download" en la parte superior derecha en la pag. principal.

Cabría también la posibilidad de usarlo en un teléfono android mediante un fichero apk, pero sería algo más complicado. De todas formas si te interesa lo puedo hacer.

Para cualquier duda no dudes en consultármelo y si te resulta útil anota una estrella en el repositorio. Gracias :)

**Comment by johnfelipe** [comment]
Que tipo de webcam usas en estos lugares públicos, cómo evitas k Las roben,
k características en ancho de banda se necesita?

**Comment by YagoLopez** [comment]
Es una recopilación de webcams de particulares, empresas e instituciones públicas (ayuntamientos por ejemplo). No las he instalado yo. Las de particulares y empresas suelen estar dentro de propiedades privadas y las de ayuntamientos en sitios altos por lo que no suelen ser fácilmente accesibles.

En realidad la aplicación utiliza una base de datos en donde están almacenadas las urls de las webcams. Accediendo a esas urls se pueden ver las imágenes.

El ancho de banda lo suministra cada propietario o institución y supongo que debe ser holgado para mantener un streaming de video. No hay un único canal por el que van los datos, cada webcam está conectada a Internet y proporciona imágenes como un servidor web. (De hecho las webcams tienen servidores web reales con su propia ip)

Si te interesa algo parecido en la zona donde tú resides, podrías hacer una búsqueda de webcams por google de tu zona, yo te podría proporcionar una copia de la base de datos que tengo alojada en google drive, tú la podrías editar y añadir las urls de las webcams que te interesen.

**Comment by johnfelipe** [comment]
Amigo, la necesidad es para poner en el website de un proyecto inmobiliario
cómo va avanzando día a día la construcción del edificio e incluso hacer al
final un vídeo de una imagen diaria, k me recomiendas para esto, veo
plausible usar tu app.
Pero no tengo idea donde poner la webcam dado k es un lote y al rededor son
casas muy chicas. K ideas me puedes dar?

**Comment by YagoLopez** [comment]
Lo siento, en eso no te puedo ayudar, no tengo experiencia.

Prueba a buscar por google, a lo mejor te da alguna idea.
